require 'uber/models/delivery/delivery'
require 'uber/models/delivery/quote'
require 'uber/models/delivery/rating'
require 'uber/models/delivery/rating_tag'
require 'uber/models/delivery/receipt'
require 'uber/models/delivery/region'